### ISSUE TITLE
Add a function for getting a column measure in pixels

### ISSUE THREAD

**Issue by callumlocke** [Financial-Times/o-grid#121]
Sometimes I just need to know the pixel width of a given number of columns (eg. to use in some custom hack or calculation). It's hard to get this info.

eg. what is the width of 5 columns (inc. interior gutters) on the `M` layout? Or what is the the full 12-column width on the `L` layout? I'd like to add a function for this:

``` scss
oGridMeasure(M, 5) // returns 240px

oGridMeasure(L, 12) // returns 940px
```

(There is the [oGridColspan()](https://github.com/Financial-Times/o-grid/blob/3ad8f982faa9854eb9fb70728e7a2bced4855bde/src/scss/_main.scss#L113-L134) function, but this returns a percentage, which isn't always usable.)

It could look something like this:

``` scss
@function oGridMeasure($layout-name, $columns, $gutters: auto) {
  @if $gutters == auto { $gutters: $columns - 1; }

  @return (
    ($columns * _oGridColumnWidth($layout-name)) +
    ($gutters * oGridGutter($layout-name))
  );
}
```

notes:
- snappy-only – it should probably throw an error if you specify a non-snappy layout like `S` (because only snappy layouts can have a straight answer for "how wide is X columns").
- this would be provided just as a low-level helper for hacks etc; obviously it's better in most cases to use the high-level mixins

Happy to do a PR for this if agreed.
