### ISSUE TITLE
Provide 'silent classes' option to suppress the direct css output of the grid module

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/o-grid#21]
The CSS Wizardry grid framework has an option for 'silent classes', which makes use of the SASS 'placeholder' selector.

https://github.com/csswizardry/csswizardry-grids#sass-silent-classes

This is achieved in that module with the following code:

``` scss
$class-type:     unquote(".");

@if $use-silent-classes == true{
    $class-type: unquote("%");
}
```

And then every rule is implemented like this:

``` scss
#{$class-type}grid{
    list-style:none;
    margin:0;
    padding:0;
    margin-left:-$gutter;
    @if $use-markup-fix != true{
        letter-spacing:-0.31em;
    }
}
```

This also means when this option is switched on unless one of the placeholder classes is one that has been extended, the compiled scss for the csswizardry-grid module is empty.

I believe there is currently no way to suppress the output of the origami grid module in the same way.
