### ISSUE TITLE
Definition of grids with different number of columns

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-grid#27]
Proposed implementation

``` scss
$_o-grid-default-column-count: 12
@mixin createGrid(
    $selector: $o-grid-selector: null // name of the class or fragment of data-o-row that wraps this grid
    $number-of-cols: $_o-grid-default-column-count
) {
   // calculate % values for columns and print out the selectors
   // output nothing if $selector is null and $number-of-cols != $_o-grid-default-column-count
  // ouput default grid if selector and $number-of-cols not defined
}
@if(!$is-silent) {
    @include createGrid();// draws the default grid
}

@include createGrid('.simplified-3-column-grid', 3);
```
