### ISSUE TITLE
Confining the grid to a container

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-grid#28]
So that e.g. `.grid-area` prefixes each of the grid stylesheet's selectors

Proposed implementation

``` scss
$o-grid-selector: null !default;

oGridWrapInSelector($o-grid-selector) {
    // the grid
}

```

Prerequisite for https://github.com/Financial-Times/o-grid-issues/issues/27
