### ISSUE TITLE
Make 'columness' more tightly tied to column width definition

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-grid#62]
I'm trying to implement a design where 3 columns turn into 2 (with the 3rd column spreading beneath the other two) when going from L to M. To achieve this I'm hampered by the fact that 'columness'

``` css
{
  float:left;
  box-sizing:border-box;
  padding-left:5px;
  padding-right:5px;
}
```

is added independently of actual column width

		@extend %o-grid-col; // adds columness
		@extend %o-grid-colspan-M6; // defines a width for the column at medium layout

I think it makes more sense to have each `colspan` declaration add the 'columness' itself, both for silent mode *and* non-silent (i.e. the `[data-o-grid-colspan]` selector should be removed and instead each e.g. `[data-o-grid-colspan~="M6"]` should add columness)

There are use cases for having columness added separate to column width (see responsiveness of menu in o-footer) but they feel like they're an abuse of what a grid should do, and the same effect could be achieved by hand-coding the wide-screen floated list styles.

**Comment by wheresrhys** [comment]
nudge @kaelig

**Comment by kaelig** [comment]
To do that in v3, you could use something like:

```scss
.col1,
.col2,
.col3 {
  @include oGridColumn;
   width: percentage(1/3); // Easier to read than oGridColumnWidth(4);
}
@include oGridRespondTo(M) {
  .col1, .col2 { width: 50%; }
  .col3 { float: none; clear: both; }
}
```
