### ISSUE TITLE
Simplify configuration to a single map?

### ISSUE THREAD

**Issue by kaelig** [Financial-Times/o-grid#65]
```scss
$o-grid-default-config: (
	columns: 12,
	gutter: 10px,
	min-width: 240px,
	max-width: 1330px,
	layouts: (
		S:  370px,  // ≥20px columns
		M:  610px,  // ≥40px columns
		L:  850px,  // ≥60px columns
		XL: 1090px  // ≥80px columns
	),
	fluid: true,
	debug: false,
	fixed-layout: M,
	enhanced-experience: true
);

// User configuration
$o-grid-user-config: () !default;

// Set a configuration setting
@mixin oGridSet($settings) {
	$o-grid-default-config: map-merge($o-grid-default-config, $settings) !global;
}

// Get a setting from the configuration
@function oGridGet($setting) {
	@return map-get($o-grid-default-config, $setting);
}

// Set user configuration
@include oGridSet($o-grid-user-config);
```

User sets their own configuration through `$o-grid-user-config`.

Large Sass frameworks do that and I think that's a pretty good way of simplifying configuration compared to the amount of scrolling required to go through all of [_variables.scss](https://github.com/Financial-Times/o-grid/blob/refactor-mqs/src/scss/_variables.scss).

Any thoughts?

Thanks to @HugoGiraudel for [the inspiration](http://www.sitepoint.com/functional-wrappers-sass/).
